# Welcome to Jekyll!
#
# Site metadata
title: Eng. Sameh Zaghloul
description: CTIO & Enterprise IT Architect | Master IT Solution Architect
author: Eng. Sameh Zaghloul
email: samah.saeed@fixed.global
url: https://sameh-zaghloul.github.io

# Theme
theme: minima

# Markdown processor
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .jekyll-cache/
  - .sass-cache/
  - gemfile
  - gemfile.lock
  - vendor/
  - temp/

# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
